import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  warlock: [{ type: "autogenerated", dirName: "warlock" }],
  mongodb: [{ type: "autogenerated", dirName: "cascade" }],
  cache: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'cache/introduction',
        'cache/quick-start',
        'cache/configurations',
        'cache/namespaces',
      ],
    },
    {
      type: 'category',
      label: 'Cache Manager',
      collapsed: true,
      items: [
        'cache/cache-manager',
        'cache/cache-driver-interface',
        'cache/base-cache-driver',
      ],
    },
    {
      type: 'category',
      label: 'Drivers',
      collapsed: true,
      items: [
        'cache/memory',
        'cache/memory-extended',
        'cache/lru-memory',
        'cache/redis',
        'cache/file',
        'cache/null',
        'cache/make-your-own-cache-driver',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Features',
      collapsed: true,
      items: [
        'cache/tags',
        'cache/events',
        'cache/atomic-operations',
        'cache/stampede-prevention',
        'cache/bulk-operations',
      ],
    },
    {
      type: 'category',
      label: 'Utilities & Guides',
      collapsed: true,
      items: [
        'cache/utils',
        'cache/comparison',
        'cache/best-practices',
      ],
    },
  ],
  seal: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,  // Keep open by default
      items: [
        'seal/getting-started/introduction',
        'seal/getting-started/installation',
        'seal/getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: true,
      items: [
        'seal/concepts/three-layer-architecture',
        'seal/concepts/validation-flow',
        'seal/concepts/error-messages',
        'seal/concepts/type-inference',
        'seal/concepts/conditional-validation',
      ],
    },
    {
      type: 'category',
      label: 'Base Validator',
      collapsed: true,
      items: [
        'seal/base-validator/index',
        'seal/base-validator/basic-rules',
        'seal/base-validator/field-comparison',
        {
          type: 'category',
          label: 'Conditional Validation',  // NESTED CATEGORY
          collapsed: true,
          items: [
            'seal/base-validator/required-rules',
            'seal/base-validator/present-rules',
          ],
        },
        'seal/base-validator/advanced',
      ],
    },
    {
      type: 'category',
      label: 'String Validator',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'seal/string-validator/index',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'seal/string-validator/mutators',
          label: 'Mutators',
        },
        {
          type: 'doc',
          id: 'seal/string-validator/validators',
          label: 'Validators',
        },
      ],
    },
    {
      type: 'category',
      label: 'Number Validator',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'seal/number-validator/index',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'seal/number-validator/mutators',
          label: 'Mutators',
        },
        {
          type: 'doc',
          id: 'seal/number-validator/validators',
          label: 'Validators',
        },
        {
          type: 'doc',
          id: 'seal/number-validator/integer',
          label: 'Integer',
        },
        {
          type: 'doc',
          id: 'seal/number-validator/float',
          label: 'Float',
        },
      ],
    },
    {
      type: 'category',
      label: 'Date Validator',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'seal/date-validator/index',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'seal/date-validator/mutators',
          label: 'Mutators',
        },
        {
          type: 'doc',
          id: 'seal/date-validator/validators',
          label: 'Validators',
        },
        {
          type: 'doc',
          id: 'seal/date-validator/transformers',
          label: 'Transformers',
        },
      ],
    },
    {
      type: 'category',
      label: 'Scalar Validator',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'seal/scalar-validator/index',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'seal/scalar-validator/validators',
          label: 'Validators',
        },
      ],
    },
    {
      type: 'category',
      label: 'Boolean Validator',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'seal/boolean-validator/index',
          label: 'Overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Any Validator',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'seal/any-validator/index',
          label: 'Overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Array Validator',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'seal/array-validator/index',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'seal/array-validator/mutators',
          label: 'Mutators',
        },
        {
          type: 'doc',
          id: 'seal/array-validator/validators',
          label: 'Validators',
        },
      ],
    },
    {
      type: 'category',
      label: 'Object Validator',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'seal/object-validator/index',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'seal/object-validator/mutators',
          label: 'Mutators',
        },
        {
          type: 'doc',
          id: 'seal/object-validator/validators',
          label: 'Validators',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsed: true,
      items: [
        'seal/advanced/custom-rules',
        'seal/advanced/plugins',
        'seal/advanced/extending-validators',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        'seal/guides/cookbook',
        'seal/guides/best-practices',
        'seal/guides/comparison',
        'seal/guides/migration',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
