import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  framework: [{ type: "autogenerated", dirName: "framework" }],
  cascade: [{ type: "autogenerated", dirName: "cascade" }],
  herald: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'herald/introduction',
        'herald/quick-start',
        'herald/core-concepts',
      ],
    },
    {
      type: 'category',
      label: 'Connecting',
      collapsed: true,
      items: [
        'herald/connecting',
        'herald/multiple-brokers',
        'herald/broker-events',
      ],
    },
    {
      type: 'category',
      label: 'Channels',
      collapsed: true,
      items: [
        'herald/channels',
        'herald/channel-options',
      ],
    },
    {
      type: 'category',
      label: 'Publishing',
      collapsed: true,
      items: [
        'herald/publishing',
        'herald/event-messages',
        'herald/publish-options',
      ],
    },
    {
      type: 'category',
      label: 'Consuming',
      collapsed: true,
      items: [
        'herald/consuming',
        'herald/event-consumers',
        'herald/consumable-decorator',
        'herald/subscribe-options',
      ],
    },
    {
      type: 'category',
      label: 'Message Handling',
      collapsed: true,
      items: [
        'herald/message-context',
        'herald/subscription-management',
        'herald/request-reply',
      ],
    },
    {
      type: 'category',
      label: 'Reliability',
      collapsed: true,
      items: [
        'herald/retries-and-dead-letters',
        'herald/error-handling',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        'herald/rabbitmq',
        'herald/best-practices',
        'herald/real-world-examples',
      ],
    },
  ],
  logger: [{ type: "autogenerated", dirName: "logger" }],
  scheduler: [{ type: "autogenerated", dirName: "scheduler" }],
  cache: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'cache/introduction',
        'cache/quick-start',
        'cache/configurations',
        'cache/namespaces',
      ],
    },
    {
      type: 'category',
      label: 'Cache Manager',
      collapsed: true,
      items: [
        'cache/cache-manager',
        'cache/cache-driver-interface',
        'cache/base-cache-driver',
      ],
    },
    {
      type: 'category',
      label: 'Drivers',
      collapsed: true,
      items: [
        'cache/memory',
        'cache/memory-extended',
        'cache/lru-memory',
        'cache/redis',
        'cache/file',
        'cache/null',
        'cache/make-your-own-cache-driver',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Features',
      collapsed: true,
      items: [
        'cache/tags',
        'cache/events',
        'cache/atomic-operations',
        'cache/stampede-prevention',
        'cache/bulk-operations',
      ],
    },
    {
      type: 'category',
      label: 'Utilities & Guides',
      collapsed: true,
      items: [
        'cache/utils',
        'cache/comparison',
        'cache/best-practices',
      ],
    },
  ],
  seal: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'seal/getting-started/introduction',
        'seal/getting-started/installation',
        'seal/getting-started/quick-start',
        'seal/getting-started/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: true,
      items: [
        'seal/concepts/three-layer-architecture',
        'seal/concepts/validation-flow',
        'seal/concepts/error-messages',
        'seal/concepts/type-inference',
        'seal/concepts/conditional-validation',
      ],
    },
    {
      type: 'category',
      label: 'Base Validator',
      collapsed: true,
      items: [
        'seal/base-validator/index',
        'seal/base-validator/basic-rules',
        'seal/base-validator/field-comparison',
        {
          type: 'category',
          label: 'Conditional Rules',
          collapsed: true,
          items: [
            'seal/base-validator/required-rules',
            'seal/base-validator/present-rules',
          ],
        },
        'seal/base-validator/advanced',
      ],
    },
    {
      type: 'category',
      label: 'Primitive Validators',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'String',
          collapsed: true,
          items: [
            { type: 'doc', id: 'seal/string-validator/index', label: 'Overview' },
            { type: 'doc', id: 'seal/string-validator/mutators', label: 'Mutators' },
            { type: 'doc', id: 'seal/string-validator/validators', label: 'Validators' },
          ],
        },
        {
          type: 'category',
          label: 'Number',
          collapsed: true,
          items: [
            { type: 'doc', id: 'seal/number-validator/index', label: 'Overview' },
            { type: 'doc', id: 'seal/number-validator/mutators', label: 'Mutators' },
            { type: 'doc', id: 'seal/number-validator/validators', label: 'Validators' },
            { type: 'doc', id: 'seal/number-validator/integer', label: 'Integer' },
            { type: 'doc', id: 'seal/number-validator/float', label: 'Float' },
            { type: 'doc', id: 'seal/number-validator/numeric', label: 'Numeric' },
          ],
        },
        {
          type: 'category',
          label: 'Date',
          collapsed: true,
          items: [
            { type: 'doc', id: 'seal/date-validator/index', label: 'Overview' },
            { type: 'doc', id: 'seal/date-validator/mutators', label: 'Mutators' },
            { type: 'doc', id: 'seal/date-validator/validators', label: 'Validators' },
            { type: 'doc', id: 'seal/date-validator/transformers', label: 'Transformers' },
          ],
        },
        { type: 'doc', id: 'seal/boolean-validator/index', label: 'Boolean' },
        {
          type: 'category',
          label: 'Scalar',
          collapsed: true,
          items: [
            { type: 'doc', id: 'seal/scalar-validator/index', label: 'Overview' },
            { type: 'doc', id: 'seal/scalar-validator/validators', label: 'Validators' },
          ],
        },
        { type: 'doc', id: 'seal/any-validator/index', label: 'Any' },
      ],
    },
    {
      type: 'category',
      label: 'Structural Validators',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Object',
          collapsed: true,
          items: [
            { type: 'doc', id: 'seal/object-validator/index', label: 'Overview' },
            { type: 'doc', id: 'seal/object-validator/mutators', label: 'Mutators' },
            { type: 'doc', id: 'seal/object-validator/validators', label: 'Validators' },
          ],
        },
        {
          type: 'category',
          label: 'Array',
          collapsed: true,
          items: [
            { type: 'doc', id: 'seal/array-validator/index', label: 'Overview' },
            { type: 'doc', id: 'seal/array-validator/mutators', label: 'Mutators' },
            { type: 'doc', id: 'seal/array-validator/validators', label: 'Validators' },
          ],
        },
        { type: 'doc', id: 'seal/record-validator/index', label: 'Record' },
        { type: 'doc', id: 'seal/tuple-validator/index', label: 'Tuple' },
      ],
    },
    {
      type: 'category',
      label: 'Special Validators',
      collapsed: true,
      items: [
        { type: 'doc', id: 'seal/union-validator/index', label: 'Union' },
        { type: 'doc', id: 'seal/computed-validator/index', label: 'Computed Fields' },
        { type: 'doc', id: 'seal/managed-validator/index', label: 'Managed Fields' },
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsed: true,
      items: [
        'seal/advanced/custom-rules',
        'seal/advanced/plugins',
        'seal/advanced/extending-validators',
        'seal/advanced/standard-schema',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        'seal/guides/cookbook',
        'seal/guides/best-practices',
        'seal/guides/comparison',
        'seal/guides/migration',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
